### ISSUE TITLE
 Propose User Tracking with Analytics Tools

### ISSUE THREAD

**Issue by MabudAlam** [Pavel401/JobScraper-Mobile#10]
### Problem
Currently, our application lacks a comprehensive user tracking system, limiting our ability to gather valuable insights into user behavior and interactions.

### Proposal
Propose a solution for implementing user tracking using analytics tools to better understand how users engage with our application.

### How would you like to see it implemented?

- Identify and suggest suitable analytics tools that align with our project goals.
- Outline the key metrics and events we should track for meaningful insights.
- Propose an implementation plan for integrating the selected analytics tools into our application.

If you have additional context, ideas, or considerations regarding user tracking with analytics tools, please share them here.

### How can we contact you (optional)

If you're open to discussion or clarification regarding your proposal, please leave your contact information (e.g., Discord handle, email) for further communication.

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by praptisharma28** [comment]
Assign me @Pavel401
