### ISSUE TITLE
Implement Scroll Back to Top Button

### ISSUE THREAD

**Issue by MabudAlam** [Pavel401/JobScraper-Mobile#11]
### Describe your improvement idea or feature request

The current user experience lacks a convenient way for users to quickly navigate back to the top of the page, especially on long-scrolling home page.
Propose the implementation of a "Scroll Back to Top" button to enhance user navigation and provide a more user-friendly experience.
pages

### How would you like to see it implemented?

Describe the benefits of adding a "Scroll Back to Top" button, such as improved user experience, increased usability, and adherence to modern design standards.

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by Anjalipriya03** [comment]
Hi!  I would like to take up the issue.
Approach to solve:
1.Using a ScrollController and a button
2.Using a ChangeNotifier for dynamic button visibility

**Comment by mukundsolanki** [comment]
I would like to work on this issue, 
my approach is to add a floating button, at first it will not be visible but as the user will scroll down it will the button will be visible
Just like a "compose" button we have seen  in Gmail.
And when the user presses the button it will smoothly scroll to the top of the listview builder.

**Comment by MabudAlam** [comment]
Closed in #13
