### ISSUE TITLE
Create a Search Bar in the App

### ISSUE THREAD

**Issue by MabudAlam** [Pavel401/JobScraper-Mobile#2]
# Description
## Problem
Currently, the JobHunt Mobile app lacks a search bar, making it challenging for users to quickly find specific job opportunities.

## Solution
Implement a search bar feature that allows users to search for job postings based on keywords, job titles, or any other relevant criteria.

# Screenshots
Include screenshots showcasing the current state of the app without the search bar and any design mockups or wireframes for the proposed search bar.

# Steps to Reproduce
Explain the steps or scenarios where the absence of a search bar is problematic for users.

# Expected Behavior
Describe the expected behavior after implementing the search bar feature.

**Comment by praptisharma28** [comment]
Hey @Pavel401 , assign me this. I will create a cool seach bar.

**Comment by praptisharma28** [comment]
https://github.com/Pavel401/JobScraper-Mobile/pull/12 @Pavel401 ,have a look and accept it under iwoc24, also add the difficult level. Thanks :)

**Comment by MabudAlam** [comment]
Hey @praptisharma28, there are a few issues with your PR. The app is throwing errors as soon as it launches.

<img width="1470" alt="Screenshot 2024-01-16 at 8 56 15 AM" src="https://github.com/Pavel401/JobScraper-Mobile/assets/47685150/7e72aee6-cbaf-410b-989e-439700b5cfd5">
<img width="1470" alt="Screenshot 2024-01-16 at 8 57 59 AM" src="https://github.com/Pavel401/JobScraper-Mobile/assets/47685150/23def5d9-8065-4cb5-93bc-07db0c6a9157">

**Comment by MabudAlam** [comment]
@praptisharma28 Please fix the issue with local db  bloc

**Comment by MabudAlam** [comment]
@praptisharma28 any update ?

**Comment by praptisharma28** [comment]
@Pavel401 , I used async and await in a function and the error is related to that only but don't worry I will resolve it. I do the PR tomorrow, no issues.

**Comment by praptisharma28** [comment]
Please have a look at my another PR @Pavel401

**Comment by MabudAlam** [comment]
> @Pavel401 , I used async and await in a function and the error is related to that only but don't worry I will resolve it. I do the PR tomorrow, no issues.

Hey @praptisharma28 did you get time to fix the error ?

**Comment by praptisharma28** [comment]
@Pavel401 , I fixed the error, will do a PR today after syncing the fork, Just wait for some hours!

**Comment by MabudAlam** [comment]
@praptisharma28 Can you please send the PR by eod ?

**Comment by praptisharma28** [comment]
https://github.com/Pavel401/JobScraper-Mobile/pull/19 did it @Pavel401 check it, also please don't forget to add the iwoc24 and difficulty level so that this PR show to my dashboard again and close the issue too and look at my other PR also please! Thanks.
