### ISSUE TITLE
[Feature]: Add the github action workflow for greeting contributors 

### ISSUE THREAD

**Issue by praptisharma28** [Pavel401/JobScraper-Mobile#21]
### Describe your improvement idea or feature request

The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

### How would you like to see it implemented?

Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by praptisharma28** [comment]
@Pavel401 assign me this here too, will do the same here too, alsoplease give the tags before merging th PR. Will keep in mind not to add "feature" label additionally. Thankyou

**Comment by MabudAlam** [comment]
@praptisharma28 before sending the PR, please share the demo. The same workflow in the Jobs Scraper repo is failing every time.

**Comment by praptisharma28** [comment]
@Pavel401 you need to raise a github token in your repo for that. You can follow any youtube video tutorial online to raise it.

**Comment by MabudAlam** [comment]
> @Pavel401 you need to raise a github token in your repo for that. You can follow any youtube video tutorial online to raise it.

Share the video tutorial :)

**Comment by praptisharma28** [comment]
found the error @Pavel401 , they were with the if condition.

**Comment by praptisharma28** [comment]
opening a new issue and pushing the change in the same branch, you can assign me there.

**Comment by praptisharma28** [comment]
https://github.com/praptisharma28/Jobs-Scraper/actions/runs/7639273071/job/20811941933?pr=7 I did the changes and updated the code in this branch, tested by an another id. They are running perfectly, you can assign me now @Pavel401

**Comment by praptisharma28** [comment]
@Pavel401 please change the tag here too if u r changing it, coz you changed it in the PR. Coz this tag will reflect to my dashboard not the PR one.

**Comment by praptisharma28** [comment]
> @Pavel401 please change the tag here too if u r changing it, coz you changed it in the PR. Coz this tag will reflect to my dashboard not the PR one.

done @Pavel401 check the pr
