### ISSUE TITLE
Feature: Add a preview for improved user experience to job card

### ISSUE THREAD

**Issue by praptisharma28** [Pavel401/JobScraper-Mobile#23]
### Describe your improvement idea or feature request

The user before getting on our website will first get to see a preview on how app works.

### How would you like to see it implemented?

Will check it on dev server.

### How can we contact you (optional)

@praptisharma282003@gmail.com

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by praptisharma28** [comment]
Assign me @Pavel401

**Comment by MabudAlam** [comment]
@praptisharma28 are you still working on this issue?

**Comment by praptisharma28** [comment]
Yes @Pavel401 , wait for some hours, giving the PR
