### ISSUE TITLE
UI improvement of the app

### ISSUE THREAD

**Issue by praptisharma28** [Pavel401/JobScraper-Mobile#25]
### What is the problem you are trying to solve?

Enhancement of the UI of the app.

### Would you like to work on this issue?

Yes, I'd like to contribute.

### By submitting this issue, I confirm that:

- [X] I have starred the repo ⭐

**Comment by MabudAlam** [comment]
@praptisharma28 What enhancements would you like to make?
Please mention them

**Comment by praptisharma28** [comment]
Like overall enhancement in each page, like beautifying the icons, buttons etc. @Pavel401 
you can assign me

**Comment by MabudAlam** [comment]
@praptisharma28 The current UI is based on Material 3 and I want to keep it simple only.
If you want to complete the search results then I can assign you this issue.

**Comment by praptisharma28** [comment]
> @praptisharma28 The current UI is based on Material 3 and I want to keep it simple only.
> If you want to complete the search results then I can assign you this issue.

May I know in detail what do you want regarding search results, so I can contribute? @Pavel401

**Comment by praptisharma28** [comment]
I can add some animations/ transitions in splash screen, lists that are opening on job card, page transition. Can I change the app logo too if you like? @Pavel401

**Comment by praptisharma28** [comment]
https://github.com/Pavel401/JobScraper-Mobile/assets/123169861/89ae13b8-6374-418b-b59e-4cd9ef3a32c3

watch this out @Pavel401 :)
