### ISSUE TITLE
Create About Screen for the App

### ISSUE THREAD

**Issue by MabudAlam** [Pavel401/JobScraper-Mobile#3]
# Description
## Problem
The JobHunt Mobile app currently lacks an About screen, which is essential for providing users with information about the app, its purpose, and acknowledging contributors.

## Solution
Design and implement a visually appealing About screen following the Material 3 design guidelines. This screen should include relevant information about the app, such as its purpose, features, and contributors.

# Design Requirements
1. **Material 3 Design:** Ensure that the design adheres to the Material 3 design guidelines for a modern and cohesive user experience.
2. **App Information:** Display essential information about the app, including its purpose, features, and any other relevant details.
3. **Acknowledgments:** Include a section acknowledging contributors, team members, or any other individuals who have contributed to the development of the app.
4. **Visual Appeal:** Create a visually appealing design that aligns with the overall aesthetics of the JobHunt Mobile app.

# Screenshots or Mockups
Provide screenshots or design mockups showcasing the proposed About screen design. Include details such as color schemes, typography, and layout.

**Comment by ShubhAgarwal0704** [comment]
Hey @Pavel401 plz assign this issue to me

**Comment by ShubhAgarwal0704** [comment]
hey @Pavel401 can you plz share some details about your app and also about yourself. Will be needing it for About Section
