### ISSUE TITLE
A dismissed Dismissible widget is still part of the tree.

### ISSUE THREAD

**Issue by afjal1** [Pavel401/JobScraper-Mobile#32]
### Describe your issue

While Dismissing a Job to add to Bookmark on HomeScreen  it showing "A dismissed Dismissible widget is still part of the tree."

Screenshot:
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-11 at 23 42 49](https://github.com/Pavel401/JobScraper-Mobile/assets/52181725/5d611d69-e2be-4939-a4ee-6898346b16b0)

### Steps to reproduce

Run Project and Dismisse any Job from Home Screen

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by afjal1** [comment]
> Hey, @afjal1 welcome to JOBHUNT MOBILE APP repository.🎊 Thank you so much for taking the time to point this out.🙌

Your welcome,
I have opened PR for fixing this

**Comment by MabudAlam** [comment]
Fixed on #33
