### ISSUE TITLE
Refactor Services for Improved Performance and Maintainability

### ISSUE THREAD

**Issue by MabudAlam** [Pavel401/JobScraper-Mobile#4]
# Description
## Problem
The current implementation of services in the JobHunt Mobile app may have areas for improvement in terms of performance, code readability, and maintainability. Identifying and addressing these issues will contribute to a more efficient and robust application.

## Solution
Refactor the services within the app to enhance performance, readability, and maintainability. Consider the following aspects during the refactoring process:

### Areas for Improvement
1. **Code Structure:** Review the current code structure and identify opportunities for modularization and organization.
2. **Performance Optimization:** Analyze the performance of existing services and implement optimizations where necessary to improve overall app responsiveness.
3. **Error Handling:** Enhance error handling mechanisms to provide informative and user-friendly error messages when issues arise.

**Comment by praptisharma28** [comment]
Assign me @Pavel401

**Comment by praptisharma28** [comment]
@Pavel401 also a suggestion , can you put your app on server so that it can help in contribution and solving this issue.
