### ISSUE TITLE
Enhance Job Card Design for Improved User Experience

### ISSUE THREAD

**Issue by MabudAlam** [Pavel401/JobScraper-Mobile#6]
# Description
## Problem
The current design of Job Cards in the JobHunt Mobile app may have room for improvement in terms of visual appeal, readability, or user interaction. Enhancing the Job Card design can contribute to a more engaging and user-friendly experience.

## Solution
Refine the design of Job Cards to improve overall aesthetics and user experience.

**Comment by praptisharma28** [comment]
Assigne me @Pavel401

**Comment by mukundsolanki** [comment]
I would like to work on this issue @Pavel401 !

**Comment by praptisharma28** [comment]
@mukundsolanki I am working on it. Wait for my PR.

**Comment by praptisharma28** [comment]
https://github.com/Pavel401/JobScraper-Mobile/pull/17 check it @Pavel401 , also don't forget to add the iwoc24 tag and difficulty level.

**Comment by praptisharma28** [comment]
@Pavel401 I have added something, I want you to have a look at it. Also a hard label would be appreciated bcoz it took me a lot of time. Thanks:)

https://github.com/Pavel401/JobScraper-Mobile/assets/123169861/ad13db9b-5848-461c-829e-51765a231243

**Comment by MabudAlam** [comment]
@praptisharma28 Amazing work, create a new issue. I will add the hard tag .

**Comment by praptisharma28** [comment]
@Pavel401 what else is wanted in this issue ? Anything more I can add?

**Comment by MabudAlam** [comment]
I think this is done; we don't need anything more.
What was the PR for this issue?

**Comment by praptisharma28** [comment]
ok np @Pavel401 , you can close it now. I just added a preview which u recently merged. that was thr PR.
