### ISSUE TITLE
README Improvement

### ISSUE THREAD

**Issue by MabudAlam** [Pavel401/JobScraper-Mobile#8]
**Add anything you want to make this read me useful**
**Add IWOC Background Image**
**Add Contributors**

**Comment by aavvvacado** [comment]
Please assign  this to me under iwoc 2024 . Also, kindly  mention what other changes you want.

**Comment by MabudAlam** [comment]
Keep the existing content of Usage & Screenshots, Features, and Configuration. Other than that, it's up to you how you want to improve the README.

**Comment by praptisharma28** [comment]
Hey @Pavel401 , can you asign me this. I will give you a PR under 30 minutes. I will contributors, workflow.md and setup.md too additionally and link them with readme.md .

**Comment by MabudAlam** [comment]
Hey @praptisharma28, this issue was already assigned to @aavvvacado yesterday. Let's wait for him to complete his work; otherwise, I will assign it to you.

**Comment by praptisharma28** [comment]
Sure @Pavel401 , no issues.

**Comment by MabudAlam** [comment]
Closed on #14
