### ISSUE TITLE
Propose a better UI design for the job card used in the App

### ISSUE THREAD

**Issue by MabudAlam** [Pavel401/JobScraper-Mobile#9]
### What is the problem you are trying to solve?

The current UI design for the job card in the app could be improved for better user experience and visual appeal.
Propose a new and enhanced UI design for the job card to make it more user-friendly, modern, and aligned with the app's overall aesthetics.
Please provide detailed information and visual representations of your proposed UI design changes. Consider including wireframes, mockups, or any other relevant materials to help illustrate your ideas.

### How can we contact you (optional)

Discord 

### Would you like to work on this issue?

None

### By submitting this issue, I confirm that:

- [X] I have starred the repo ⭐

**Comment by praptisharma28** [comment]
Assign me @Pavel401

**Comment by praptisharma28** [comment]
https://github.com/Pavel401/JobScraper-Mobile/pull/17 Have a look @Pavel401 , I did my part!
